# Generated by Django 2.2.3 on 2019-08-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-id'], 'verbose_name': '动漫', 'verbose_name_plural': '动漫'},
        ),
    ]
