# Generated by Django 2.2.3 on 2019-08-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20190705_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': '来源', 'verbose_name_plural': '来源'},
        ),
    ]
